# Generated by Django 5.2 on 2025-04-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='autors',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='category',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Опубликовано'), ('DRAFT', 'Черновик'), ('DELETED', 'Удалено'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая новость')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.newstag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новостная статья',
                'verbose_name_plural': 'Новостные статьи',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='NewsCollection',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
