# Generated by Django 5.2 on 2025-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Принята на рассмотрение'), ('IN_PROGRESS', 'Работы ведутся'), ('COMPLETED', 'Работы завершены'), ('REJECTED', 'Отказано')], default='PENDING_REVIEW', max_length=20, verbose_name='Статус'),
        ),
    ]
