# Generated by Django 5.2 on 2025-04-27 11:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ticketgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographic location (longitude, latitude)', srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketgroup',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticketgroup',
            name='last_created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания последней заявки'),
        ),
        migrations.AlterField(
            model_name='ticketgroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
