# Generated by Django 5.2 on 2025-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_description_alter_ticket_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(default='Улица Пушкина', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
