# Generated by Django 5.2 on 2025-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketcategory_score_tickettype_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
